consumes:
- application/json
definitions:
  app.ApiJson:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  v1.LoginParam:
    properties:
      loginName:
        type: string
      password:
        type: string
    required:
    - loginName
    - password
    type: object
  v1.RegisterParam:
    properties:
      displayName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - displayName
    - email
    - password
    type: object
info:
  contact:
    email: axiangcoding@gmail.com
    name: axiangcoding
  description: api system build by ax-web
  license: {}
  title: axiangcoding/anton-star
  version: 1.0.0
paths:
  /v1/cqhttp/receive/event:
    post:
      parameters:
      - description: getParam
        in: body
        name: param
        required: true
        schema:
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiJson'
      security:
      - AppToken: []
      summary: 接收cqhttp的事件
      tags:
      - CQHttp API
  /v1/cqhttp/status:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiJson'
      summary: 获取cqhttp的最新状态
      tags:
      - CQHttp API
  /v1/system/info:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiJson'
      summary: System Info
      tags:
      - System API
  /v1/user/login:
    post:
      parameters:
      - description: login param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.LoginParam'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiJson'
      tags:
      - User API
  /v1/user/me:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiJson'
      tags:
      - User API
  /v1/user/register:
    post:
      parameters:
      - description: register param
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/v1.RegisterParam'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiJson'
      tags:
      - User API
produces:
- application/json
securityDefinitions:
  AppToken:
    in: query
    name: app_token
    type: apiKey
swagger: "2.0"
