version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/api-system"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/browser-client"
    schedule:
      interval: "weekly"
