# 部署的样例，仅作为样例，生产环境采用独立的配置
version: "3"
services:
  db:
    image: mariadb:10
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootP@ssword
      MYSQL_USER: antonstar
      MYSQL_PASSWORD: AntonStarP@ssword.
      MYSQL_DATABASE: anton_star
    ports:
      - "3306:3306"
    volumes:
      - ./volume/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis:6-alpine
    # restart: always
    ports:
      - "6379:6379"
  mq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  api-system:
    build: ./api-system
    ports:
      - "8888:8888"
    volumes:
      - ./volume/api-system/app.toml:/app/config/app.toml
    depends_on:
      - db
      - mq
      - redis
  web-client:
    build: ./web-client
    ports:
      - "8080:80"
  data-crawler:
    build: ./data-crawler
    volumes:
      - ./volume/data-crawler/settings.py:/app/crawler/settings.py
    depends_on:
      - mq
      - db