# 该文件设置为开发使用

# 通用配置项
[app]
# 版本号，会被环境变量覆盖
version = "v1.0.0"
# 项目名称
name = "github.com/axiangcoding/antonstar-bot"

[app.log]
# 打印的最低日志等级，可选项 debug|info|error|fatal|panic
level = "INFO"
# 文件日志的存放路径
file.dir = "./logs/"
# 文件日志的格式，可选项 json|console
file.encoder = "json"

[app.auth]
# session加密密钥
session.encrypt_secret = "r@ndomSecretForSign"
# cookie过期时间
session.max_age = "12h"

[app.swagger]
# 是否启用swagger
enable = true

# 数据库配置相关
[app.data.db]
# 数据库连接字段
source = "host=localhost user=antonstar password=AntonStarP@ssword. dbname=anton_star port=5432 sslmode=disable"
# 最大连接数
max_open_conn = 100
# 最大空闲连接数
max_idle_conn = 10

# 缓存配置相关
[app.data.cache]
# redis连接字段
source = "redis://localhost:6379/0"

# cqhttp的配置项
[app.service.cqhttp]
# cqhttp对外端口地址
url = "http://localhost:5700"
# 配置的qq号
self_qq = 3547589750
# cqhttp http签名密钥
secret = "something like it"


[server]
# 运行模式，可选项 debug|release
run_mode = "debug"
# 运行端口
port = 8888
# 基本路径
base_path = "/"




