[app]
version = "v2.x"
name = "github.com/axiangcoding/ax-web"

[app.log]
level = "INFO"
file.enable = true
file.encoder = "json"
file.path = "./logs/"

[app.auth]
secret = "r@ndomSecretForSign"
expire_duration = "12h"
casbin_model_path = "./config/default/"
casbin_policy_adapter = "local"
casbin_policy_path = "./config/default/"

[app.swagger]
enable = true

[app.data.database]
driver = "postgres"
source = "host=localhost user=antonstar password=AntonStarP@ssword. dbname=anton_star port=5432 sslmode=disable"
max_open_conn = 100
max_idle_conn = 10

[app.data.cache]
# only support cache for now
driver = "redis"
source = "redis://localhost:6379/0"

[app.service.cqhttp]
url = "http://localhost:5700"
self_qq = 3547589750


[app.response]
# hide error details
hide_error_details = false

[server]
run_mode = "debug"
port = 8888
base_path = "/api"
app_token = "defaultAccessToken"




