version: "3"
services:
  db:
    image: mariadb:10
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootP@ssword
      MYSQL_USER: antonstar
      MYSQL_PASSWORD: AntonStarP@ssword.
      MYSQL_DATABASE: anton_star
    ports:
      - "3306:3306"
    volumes:
      - ./volume/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis:6-alpine
    # restart: always
    ports:
      - "6379:6379"